spring:
  application:
    name: JLPT Companion
  datasource:
    url: jdbc:postgresql://localhost:5432/jlptcompanion
    username: jlpt_user
    password: jlpt_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379
      # password: your_redis_password # for prod

management:
  endpoints.web.exposure.include: health,info
  endpoint.health.show-details: when_authorized

server:
  port: 8080